# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:tensura_bot.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Telegram Bot Credentials
bot.name=slizrobobot
bot.token=8616828558:AAEEevfuvc6zN4lVg7Uxyt3d3C4JVyimIHc
bot.admin.id=6112843760

# Web Server Configuration
spring.main.web-application-type=servlet
server.port=8085
