# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:tensura_bot.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Telegram Bot Credentials (specify your token here)
bot.name=TensuraSlimeRpgBot
bot.token=
bot.admin.id=0

# Web Server Configuration
spring.main.web-application-type=servlet
server.port=8085
